
services:
  backend:
    image: aibek1998/e-commerce-backend
    build:
      context: .
      dockerfile: backend/Dockerfile

    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    image: aibek1998/e-commerce
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Монтируем папку frontend в контейнер
    env_file:
      - .env
    depends_on:
      - backend